### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by ldesmarets** [woody-wordpress/woody-cli#1]
Hello, during set-up using you doc i can't make the ` ./bin/woody deploy:site`

It seems to have a wrong path in woody-command.php, in fact the doc said that you need to create /conf/sites/mySite.yaml but the woody-command.php search a /current/ directory and a .env file.
Anyway i tried to replace the path but i didn't succeed.

woody-command.php Line, 157, 179 ...

Doc.

> Create a configuration file for each of your sites in "config/sites".
My first project is called "mywebsite", so I create the file "config/sites/mywebsite.yml". > 

@leopoiroux 
Thank you

**Comment by ldesmarets** [comment]
Thank you, i read that, and there's a file in my /config/sites directory but it doesn't work.
Where's the .env ?
![Capture d’écran 2021-02-17 à 17 00 12](https://user-images.githubusercontent.com/205672/108231359-f8728600-7141-11eb-8645-3414cc29005e.png)
@leopoiroux

**Comment by leopoiroux** [comment]
Hello Laurent,
Indeed, it is a mistake in the documentation, we will correct it in our future version. You should not create a ".yml" file but create a directory like that "config/sites/mywebsite/.env".

Thank you for your interest in our product. You are the first contact we have on a use of our "opensource" version. We welcome your feedback.

Thank you and have a nice day
